language: cpp
sudo: required
dist: bionic
compiler:
  - clang
os:
  - linux
branches:
  only:
    - master
before_install:
  - sudo apt remove -y cmake
  - sudo snap install cmake --classic

script:
  - cmake --version
  - git clone https://github.com/igor-chalenko/cmake-utilities.git
  - cd cmake-utilities
  - mkdir build && cd build
  - cmake ..
  - make test install
  - cd ..
  - mkdir build && cd build
  - cmake ..
  - make test
