list(APPEND CMAKE_MODULE_PATH "../externals/cmake-utilities/cmake")
include(../cmake/AddDocs.cmake)

function(test_create_targets)
    _doxygen_set(OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
    _doxygen_set(GENERATE_HTML ON)
    _doxygen_set(GENERATE_LATEX ON)
    #_JSON_set(doxygen.output-latex.generate-latex true)
    _doxygen_set(GENERATE_PDF true)

    #add_custom_target(_test COMMAND "${CMAKE_COMMAND} --version")
    _doxygen_set(INPUT_TARGET main)
    _doxygen_set(TARGET_NAME "doxygen_docs")
    _doxygen_set(PROJECT_FILE cmake/Doxyfile2)
    configure_file(cmake/Doxyfile2
            ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile2 @ONLY)
    _doxygen_create_generate_docs_target()
    _doxygen_create_open_targets()

    if (NOT TARGET doxygen_docs)
        assert_fail("doxygen target `doxygen_docs` was not created")
    endif()
    if (NOT TARGET doxygen_docs.open_html)
        assert_fail("The target `doxygen_docs.open_html` was not created")
    endif()
    if (NOT TARGET doxygen_docs.open_latex)
        assert_fail("The target `doxygen_docs.open_latex` was not created")
    endif()
    if (NOT TARGET doxygen_docs.open_pdf)
        assert_fail("The target `doxygen_docs.open_pdf` was not created")
    endif()
endfunction()

test_create_targets()