function(test_global_map_get_set_append)
    global_map_set(property "value")
    global_map_append(property "value2")
    global_map_get(property _new_value)
    assert_same("${_new_value}" "value;value2")
endfunction()

function(test_global_map_clear_scope)
    global_map_set(output-xml.generate-xml_INPUT GENERATE_XML)
    global_map_set(output-xml.generate-xml_SETTER "set_generate_xml")

    global_map_get(output-xml.generate-xml_INPUT _xml)
    assert_same("${_xml}" "GENERATE_XML")
    global_map_get(output-xml.generate-xml_SETTER _setter)
    assert_same("${_setter}" "set_generate_xml")
    global_map_clear_scope()
    global_map_get(output-xml.generate-xml_INPUT _xml)
    assert_same("${_xml}" "")
    global_map_get(output-xml.generate-xml_SETTER _setter)
    assert_same("${_setter}" "")
endfunction()

test_global_map_get_set_append()
test_global_map_clear_scope()

